name: Continuous Integration

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y [Your dependencies here]

    - name: Build Docker Image
      run: |
        docker build -t myapp:latest .

    - name: Run Tests
      run: |
        docker run myapp:latest python -m unittest discover
